"""In-scope Java *Test class → rewrite wave.

Every class with a public test* must appear here or in EXCLUDED_TESTS.
"""

from __future__ import annotations

# Java-runtime-only. Each has a named replacement in STATUS.md.
EXCLUDED_TESTS: frozenset[str] = frozenset(
    {
        "org.omegat.LanguageModuleContentTest",
        "org.omegat.core.ModuleDistributionSmokeTest",
        "org.omegat.core.data.PluginInformationTest",
        "org.omegat.util.gui.StaticUIUtilsTest",
        "org.omegat.util.gui.StylesTest",
        "svn.BundleTest",
        "svn.PluginsTest",
    }
)

# Wave id used in WAVE_REQUIRED_TESTS / STATUS notes (R1–R10).
# Classes with 0 public test* still listed so they cannot hide.
WAVE_REQUIRED_TESTS: dict[str, tuple[str, ...]] = {
    "R1": (
        "org.omegat.core.KnownExceptionTest",
        "org.omegat.core.data.ExternalTMFactoryTest",
        "org.omegat.core.data.MergeTest",
        "org.omegat.core.data.AutoTmxTest",
        "org.omegat.core.data.ProjectPropertiesTest",
        "org.omegat.core.data.RealProjectTest",
        "org.omegat.core.data.TmxSegmentationTest",
        "org.omegat.core.data.TokenTest",
        "org.omegat.core.matching.LevenshteinDistanceTest",
        "org.omegat.core.search.SearcherTest",
        "org.omegat.core.segmentation.SRXManagerTest",
        "org.omegat.core.segmentation.SRXTest",
        "org.omegat.core.segmentation.SegmenterTest",
        "org.omegat.core.statistics.CalcMatchStatisticsTest",
        "org.omegat.core.statistics.CalcStandardStatisticsTest",
        "org.omegat.core.statistics.FindMatchesTest",
        "org.omegat.core.statistics.StatisticsTest",
        "org.omegat.core.statistics.StatsResultTest",
        "org.omegat.core.tagvalidation.TagRepairTest",
        "org.omegat.core.tagvalidation.TagValidationTest",
        "org.omegat.util.BiDiUtilsTest",
        "org.omegat.util.EncodingDetectorTest",
        "org.omegat.util.FileUtilTest",
        "org.omegat.util.HttpConnectionUtilsTest",
        "org.omegat.util.JsonParserTest",
        "org.omegat.util.LanguageTest",
        "org.omegat.util.MagicCommentTest",
        "org.omegat.util.MixedEolHandlingReaderTest",
        "org.omegat.util.OStringsTest",
        "org.omegat.util.PatternConstsTest",
        "org.omegat.util.PreferencesTest",
        "org.omegat.util.ProjectFileStorageTest",
        "org.omegat.util.StaticUtilsTest",
        "org.omegat.util.StringUtilTest",
        "org.omegat.util.TMXDateParserTest",
        "org.omegat.util.TMXReaderTest",
        "org.omegat.util.TMXWriterTest",
        "org.omegat.util.TagUtilTest",
        "org.omegat.util.TmxEscapingWriterTest",
        "org.omegat.util.VersionTest",
        "org.omegat.util.XMLStreamReaderTest",
        "org.omegat.util.html.EntityUtilTest",
    ),
    "R2": (
        "org.omegat.filters.AndroidFilterTest",
        "org.omegat.filters.DocBookFilterTest",
        "org.omegat.filters.DokuWikiFilterTest",
        "org.omegat.filters.FiltersTest",
        "org.omegat.filters.HHCFilter2Test",
        "org.omegat.filters.HTMLFilter2Test",
        "org.omegat.filters.HelpAndManualFilterTest",
        "org.omegat.filters.ILIASFilterTest",
        "org.omegat.filters.INIFilterTest",
        "org.omegat.filters.LatexFilterTest",
        "org.omegat.filters.MagentoFilterTest",
        "org.omegat.filters.MoodlePHPFilterTest",
        "org.omegat.filters.MozillaDTDFilterTest",
        "org.omegat.filters.MozillaFTLFilterTest",
        "org.omegat.filters.OpenDocFilterTest",
        "org.omegat.filters.OpenXMLFilterTest",
        "org.omegat.filters.POFilterTest",
        "org.omegat.filters.PdfFilterTest",
        "org.omegat.filters.RcFilterTest",
        "org.omegat.filters.RelaxNGFilterTest",
        "org.omegat.filters.ResXFilterTest",
        "org.omegat.filters.ResourceBundleFilterTest",
        "org.omegat.filters.SrtFilterTest",
        "org.omegat.filters.SvgFilterTest",
        "org.omegat.filters.TextFilterTest",
        "org.omegat.filters.WiXFilterTest",
        "org.omegat.filters.XHTMLFilterTest",
        "org.omegat.filters.XLIFFFilterTest",
        "org.omegat.filters.XMLSpreadsheetTest",
        "org.omegat.filters.YamlFilterTest",
        "org.omegat.filters2.latex.LatexFilterUnitTest",
        "org.omegat.filters2.master.FilterMasterTest",
        "org.omegat.filters2.master.PluginUtilsTest",
        "org.omegat.filters2.text.LineLengthLimitWriterTest",
        "org.omegat.filters3.XMLFilterTest",
        "org.omegat.filters4.MsOfficeFileFilterTest",
        "org.omegat.filters4.Xliff1FilterTest",
        "org.omegat.filters4.Xliff2FilterTest",
        "org.omegat.filters4.xml.openxml.OpenXmlFilterTest",
    ),
    "R3": (
        "org.omegat.tokenizer.BaseTokenizerTest",
        "org.omegat.tokenizer.DefaultTokenizerTest",
        "org.omegat.tokenizer.HunspellTokenizerTest",
        "org.omegat.tokenizer.TokenizerTest",
    ),
    "R4": (
        "org.omegat.core.dictionaries.DictionariesManagerTest",
        "org.omegat.core.dictionaries.DictionaryDataTest",
        "org.omegat.core.dictionaries.LingvoDSLTest",
        "org.omegat.core.dictionaries.StarDictTest",
        "org.omegat.core.spellchecker.SpellCheckerManagerTest",
        "org.omegat.languagetools.FalseFriendsTest",
        "org.omegat.languagetools.LanguageToolTest",
    ),
    "R5": (
        "org.omegat.gui.editor.DocumentFilter3Test",
        "org.omegat.gui.editor.EditorControllerTest",
        "org.omegat.gui.editor.EditorUtilsTest",
        "org.omegat.gui.editor.SegmentExportImportTest",
        "org.omegat.gui.editor.history.WordCompleterTest",
        "org.omegat.gui.editor.history.WordPredictorTest",
        "org.omegat.gui.editor.mark.AltTranslationsMarkerTest",
        "org.omegat.gui.editor.mark.BiDiMarkersTest",
        "org.omegat.gui.editor.mark.ComesFromAutoTMMarkerTest",
        "org.omegat.gui.editor.mark.ComesFromMTMarkerTest",
        "org.omegat.gui.editor.mark.MarkerColorFreshnessTest",
        "org.omegat.gui.editor.mark.NBSPMarkerTest",
        "org.omegat.gui.editor.mark.ProtectedPartsMarkerTest",
        "org.omegat.gui.editor.mark.RemoveTagMarkerTest",
        "org.omegat.gui.editor.mark.ReplaceMarkerTest",
        "org.omegat.gui.editor.mark.WhitespaceMarkerTest",
        "org.omegat.util.editor.EditorUtilsTest",
    ),
    "R6": (
        "org.omegat.gui.glossary.GlossaryAutoCompleterViewTest",
        "org.omegat.gui.glossary.GlossaryEntryTest",
        "org.omegat.gui.glossary.GlossaryReaderCSVTest",
        "org.omegat.gui.glossary.GlossaryReaderTBXTest",
        "org.omegat.gui.glossary.GlossaryReaderTSVTest",
        "org.omegat.gui.glossary.GlossarySearcherTest",
        "org.omegat.gui.glossary.GlossaryTextAreaTest",
        "org.omegat.gui.glossary.TransTipsMarkerTest",
        "org.omegat.gui.issues.IssueCheckerTest",
        "org.omegat.gui.issues.IssueProvidersTest",
        "org.omegat.gui.issues.IssuesTableModelTest",
        "org.omegat.gui.issues.IssuesTypeListModelTest",
        "org.omegat.gui.issues.SimpleIssueTest",
        "org.omegat.gui.issues.TerminologyIssueProviderTest",
        "org.omegat.gui.matches.FindMatchesThreadTest",
        "org.omegat.gui.matches.MatchesTextAreaTest",
        "org.omegat.gui.matches.MatchesVarExpansionTest",
        "org.omegat.gui.notes.NotesTextAreaTest",
    ),
    "R7": (
        "org.omegat.gui.dialogs.DialogsTest",
        "org.omegat.gui.filelist.ProjectFilesListControllerTest",
        "org.omegat.gui.main.MainWindowMenuTest",
        "org.omegat.gui.main.ProjectUICommandsTest",
        "org.omegat.gui.scripting.ScriptItemTest",
        "org.omegat.gui.scripting.ScriptRunnerTest",
        "org.omegat.gui.scripting.ScriptingTest",
        "org.omegat.gui.search.SearchWindowTest",
        "org.omegat.gui.shortcuts.PropertiesShortcutsTest",
    ),
    "R8": (
        "org.omegat.core.machinetranslators.MachineTranslatorsManagerTest",
        "org.omegat.externalfinder.ExternalFinderTest",
    ),
    "R9": (
        "org.omegat.core.team2.RemoteRepositoryFactoryTest",
        "org.omegat.core.team2.RemoteRepositoryProvider2Test",
        "org.omegat.core.team2.RemoteRepositoryProviderTest",
        "org.omegat.core.team2.impl.HTTPRemoteRepositoryTest",
    ),
    "R10": (
        "org.omegat.MainTest",
        "org.omegat.cli.CommandCommonTest",
        "org.omegat.cli.LegacyParametersTest",
        "org.omegat.gui.align.AlignSettingsPersistenceTest",
        "org.omegat.gui.align.AlignerTest",
        "org.omegat.gui.align.BundleTest",
    ),
}

# STATUS table still uses P1–P12. Map R-wave required sets onto those cells
# so a false P-row parity still fails.
STATUS_WAVE_ALIASES: dict[str, str] = {
    "P1": "R1",
    "P2": "R2",
    "P3": "R2",
    "P4": "R2",
    "P5": "R3",
    "P6": "R4",
    "P7": "R5",
    "P8": "R7",
    "P9": "R8",
    "P10": "R9",
    "P11": "R10",
}
