/** Migrated from reference/java/src/docs/tips/en/tips.yaml */
export const TIPS = [
  { name: "Associate file formats", body: "File filters decide how source files are parsed. Open Options → File Filters to change masks and options; those keys are sent to parse/write." },
  { name: "Call user manual", body: "Press F1 to open the user manual shipped with the desktop package." },
  { name: "Automatic backup", body: "Project save writes project_save.tmx and a .bak copy. Autosave seconds live in Preferences → Save." },
  { name: "How to download dictionary", body: "Spell dictionaries are Hunspell aff/dic pairs. Missing languages download into the config spell folder on first use." },
  { name: "Bridge two languages with an intermediate TM", body: "Put a TMX in tm/tmx2source named after the other language to populate the source-side alternate." },
  { name: "OmegaT theme", body: "Appearance stores light/dark plus UI and editor fonts. The accent is ink vermilion #9B2C1A." },
  { name: "Create your own translation memories", body: "Compile exports omegat, level1 and level2 TMX next to the project or the export TM folder." },
  { name: "Restore the default window layout", body: "View → Restore Default GUI reloads the DockingDefaults ratios (notes/glossary on top, editor centre, matches below)." },
  { name: "Install dictionaries", body: "StarDict needs .ifo + .idx + .dict or .dict.dz. DSL accepts .dsl.dz." },
  { name: "Unlock the cursor with F2", body: "The segment editor is a token document: tags are protected spans. Enter commits and advances." },
  { name: "Choose a folder for exported TMs", body: "Set export_tm_levels and the export TM folder in project properties / Save preferences." },
  { name: "The writable glossary glossary.txt", body: "Edit → Create Glossary Entry appends to the project writable glossary and refreshes glossary.query." },
  { name: "Navigate and insert from Fuzzy Matches", body: "Ctrl+1…5 overwrite with matches 1–5. Ctrl+I inserts, Ctrl+R overwrites the selected match." },
  { name: "Default layout overview", body: "Nine docks: Editor, Matches, Glossary, Dictionary, MT, Notes, Comments, Multiple, Segment Properties. Files and Issues are windows." },
  { name: "Project folder default structure", body: "source/, target/, tm/, glossary/, dictionary/, omegat/project_save.tmx — same as Java OmegaT." },
  { name: "tm/auto folder", body: "Exact matches in tm/auto populate empty targets when the project opens." },
  { name: "tm/enforce overwrite", body: "tm/enforce overwrites the segment even if a translation already exists." },
  { name: "tm/mt folder highlights inserted matches", body: "Machine-translation TMX in tm/mt is scored and marked as MT origin." },
  { name: "Apply penalties to matches with tm/penalty-xxx", body: "A folder named tm/penalty-10 subtracts 10 from every match loaded from it." },
  { name: "Use Check Issues for tag problems", body: "Tools → Check Issues lists tag, spell, glossary and LanguageTool findings and jumps to the segment." },
  { name: "Ignore a word in the dictionary", body: "Learn and Ignore write the project learned/ignored word lists and refresh immediately." },
];
