// SPDX-License-Identifier: GPL-3.0-or-later

use serde::Deserialize;
use std::collections::BTreeSet;
use std::fmt::Write as _;
use std::path::PathBuf;

#[derive(Deserialize)]
#[serde(deny_unknown_fields)]
struct Registry {
    version: u8,
    methods: Vec<Method>,
}

#[derive(Deserialize)]
#[serde(deny_unknown_fields)]
struct Method {
    method: String,
    writer: Option<Writer>,
}

#[derive(Deserialize)]
#[serde(deny_unknown_fields)]
struct Writer {
    scope: String,
    activation: String,
    receipt_route: String,
    journal_operation: String,
    watches_project_inputs: bool,
}

fn enum_variant(value: &str, allowed: &[(&str, &'static str)], field: &str) -> &'static str {
    allowed
        .iter()
        .find_map(|(name, variant)| (*name == value).then_some(*variant))
        .unwrap_or_else(|| panic!("unsupported {field} {value:?} in rpc-methods.json"))
}

fn main() {
    println!("cargo:rerun-if-changed=rpc-methods.json");
    let bytes = std::fs::read("rpc-methods.json").expect("read rpc-methods.json");
    let registry: Registry =
        serde_json::from_slice(&bytes).expect("parse canonical sidecar RPC registry");
    assert_eq!(registry.version, 1, "unsupported RPC registry version");

    let mut methods = BTreeSet::new();
    let mut writer_methods = BTreeSet::new();
    let mut project_writers = 0;
    let mut config_writers = 0;
    for entry in &registry.methods {
        assert!(!entry.method.is_empty(), "RPC method must not be empty");
        assert!(
            methods.insert(entry.method.as_str()),
            "duplicate RPC method {}",
            entry.method
        );
        if let Some(writer) = &entry.writer {
            assert!(
                writer_methods.insert(entry.method.as_str()),
                "duplicate writer {}",
                entry.method
            );
            match writer.scope.as_str() {
                "project" => project_writers += 1,
                "config" => config_writers += 1,
                other => panic!("unsupported writer scope {other:?}"),
            }
            enum_variant(
                &writer.activation,
                &[
                    ("always", "Always"),
                    ("persist_true", "PersistTrue"),
                    ("recovery", "Recovery"),
                ],
                "writer activation",
            );
            enum_variant(
                &writer.receipt_route,
                &[
                    ("caller", "Caller"),
                    ("recovery", "Recovery"),
                    ("config", "Config"),
                ],
                "receipt route",
            );
            assert!(
                !writer.journal_operation.is_empty(),
                "writer {} has an empty journal operation",
                entry.method
            );
            if writer.scope == "config" {
                assert!(
                    !writer.watches_project_inputs,
                    "config writer {} cannot watch project inputs",
                    entry.method
                );
            }
        }
    }
    assert_eq!(
        writer_methods.len(),
        26,
        "writer catalog must contain 26 rows"
    );
    assert_eq!(
        project_writers, 22,
        "writer catalog must contain 22 project rows"
    );
    assert_eq!(
        config_writers, 4,
        "writer catalog must contain 4 config rows"
    );

    let mut generated = String::from(
        "// @generated by crates/omegat-ipc/build.rs from rpc-methods.json.\n\
         // Do not edit this file by hand.\n\
         pub const RPC_REGISTRY_VERSION: u8 = ",
    );
    writeln!(&mut generated, "{};", registry.version).unwrap();
    generated.push_str("pub const RPC_METHOD_REGISTRY: &[RpcMethodSpec] = &[\n");
    for entry in &registry.methods {
        writeln!(
            &mut generated,
            "    RpcMethodSpec {{ method: {:?}, writer: {} }},",
            entry.method,
            match &entry.writer {
                None => "None".to_string(),
                Some(writer) => {
                    let scope = enum_variant(
                        &writer.scope,
                        &[("project", "Project"), ("config", "Config")],
                        "writer scope",
                    );
                    let activation = enum_variant(
                        &writer.activation,
                        &[
                            ("always", "Always"),
                            ("persist_true", "PersistTrue"),
                            ("recovery", "Recovery"),
                        ],
                        "writer activation",
                    );
                    let route = enum_variant(
                        &writer.receipt_route,
                        &[
                            ("caller", "Caller"),
                            ("recovery", "Recovery"),
                            ("config", "Config"),
                        ],
                        "receipt route",
                    );
                    format!(
                        "Some(WriterSpec {{ scope: WriterScope::{scope}, \
                         activation: WriterActivation::{activation}, \
                         receipt_route: ReceiptRoute::{route}, \
                         journal_operation: {:?}, watches_project_inputs: {} }})",
                        writer.journal_operation, writer.watches_project_inputs
                    )
                }
            }
        )
        .unwrap();
    }
    generated.push_str("];\n");
    generated.push_str("pub const WRITER_CATALOG: &[WriterCatalogEntry] = &[\n");
    for entry in registry
        .methods
        .iter()
        .filter(|entry| entry.writer.is_some())
    {
        let writer = entry.writer.as_ref().unwrap();
        let scope = enum_variant(
            &writer.scope,
            &[("project", "Project"), ("config", "Config")],
            "writer scope",
        );
        let activation = enum_variant(
            &writer.activation,
            &[
                ("always", "Always"),
                ("persist_true", "PersistTrue"),
                ("recovery", "Recovery"),
            ],
            "writer activation",
        );
        let route = enum_variant(
            &writer.receipt_route,
            &[
                ("caller", "Caller"),
                ("recovery", "Recovery"),
                ("config", "Config"),
            ],
            "receipt route",
        );
        writeln!(
            &mut generated,
            "    WriterCatalogEntry {{ method: {:?}, scope: WriterScope::{scope}, \
             activation: WriterActivation::{activation}, \
             receipt_route: ReceiptRoute::{route}, journal_operation: {:?}, \
             watches_project_inputs: {} }},",
            entry.method, writer.journal_operation, writer.watches_project_inputs
        )
        .unwrap();
    }
    generated.push_str("];\n");

    let destination =
        PathBuf::from(std::env::var_os("OUT_DIR").expect("OUT_DIR")).join("rpc_registry.rs");
    std::fs::write(destination, generated).expect("write generated RPC registry");
}
