import { Menu, type BrowserWindow, type MenuItemConstructorOptions } from "electron";
import { t } from "../renderer/i18n";

function send(win: BrowserWindow, action: string, payload?: unknown) {
  win.webContents.send("menu:action", action, payload);
}

function item(
  win: BrowserWindow,
  label: string,
  action: string,
  accelerator?: string,
  extra?: Partial<MenuItemConstructorOptions>,
): MenuItemConstructorOptions {
  return {
    label,
    accelerator,
    click: () => send(win, action),
    ...extra,
  };
}

/** Java `MainMenuShortcuts.properties` (ctrl → CmdOrCtrl). Labels come from UI locale catalogs. */
export function buildApplicationMenu(win: BrowserWindow, tr: (key: string) => string = t): Menu {
  const template: MenuItemConstructorOptions[] = [
    {
      label: tr("menuProject"),
      submenu: [
        item(win, tr("newProject"), "project.new", "CmdOrCtrl+Shift+N"),
        item(win, tr("team"), "project.team-new"),
        item(win, tr("openProject"), "project.open", "CmdOrCtrl+O"),
        { label: tr("recent"), role: "recentDocuments" },
        { type: "separator" },
        item(win, tr("importFiles"), "project.import"),
        item(win, tr("wiki"), "project.wiki"),
        item(win, tr("reload"), "project.reload", "F5"),
        item(win, tr("close"), "project.close", "CmdOrCtrl+Shift+W"),
        { type: "separator" },
        item(win, tr("save"), "project.save", "CmdOrCtrl+S"),
        { type: "separator" },
        item(win, tr("commitSource"), "project.commit-source"),
        item(win, tr("commitTarget"), "project.commit-target"),
        { type: "separator" },
        item(win, tr("compile"), "project.compile", "CmdOrCtrl+D"),
        item(win, tr("compileSingle"), "project.compile-single", "CmdOrCtrl+Shift+D"),
        item(win, tr("med"), "project.med"),
        { type: "separator" },
        item(win, tr("properties"), "project.edit", "CmdOrCtrl+E"),
        item(win, tr("files"), "project.files", "CmdOrCtrl+L"),
        {
          label: tr("accessProject"),
          submenu: [
            item(win, tr("accessRoot"), "project.access-root"),
            item(win, tr("accessDict"), "project.access-dict"),
            item(win, tr("accessGlossary"), "project.access-glossary"),
            item(win, tr("accessSource"), "project.access-source"),
            item(win, tr("accessTarget"), "project.access-target"),
            item(win, tr("accessTm"), "project.access-tm"),
            item(win, tr("accessExportTm"), "project.access-export-tm"),
            { type: "separator" },
            item(win, tr("accessCurrentSource"), "project.access-current-source"),
            item(win, tr("accessCurrentTarget"), "project.access-current-target"),
            item(win, tr("accessWritableGlossary"), "project.access-writable-glossary"),
          ],
        },
        { type: "separator" },
        { role: "quit", label: tr("quit"), accelerator: "CmdOrCtrl+Q" },
      ],
    },
    {
      label: tr("menuEdit"),
      submenu: [
        item(win, tr("undo"), "edit.undo", "CmdOrCtrl+Z"),
        item(win, tr("redo"), "edit.redo", "CmdOrCtrl+Y"),
        { type: "separator" },
        item(win, tr("overwriteTranslation"), "edit.overwrite-translation", "CmdOrCtrl+R"),
        item(win, tr("insertTranslation"), "edit.insert-translation", "CmdOrCtrl+I"),
        item(win, tr("overwriteMt"), "edit.overwrite-mt", "CmdOrCtrl+M"),
        item(win, tr("overwriteSource"), "edit.overwrite-source", "CmdOrCtrl+Shift+R"),
        item(win, tr("insertSource"), "edit.insert-source", "CmdOrCtrl+Shift+I"),
        item(win, tr("selectSource"), "edit.select-source", "CmdOrCtrl+Shift+A"),
        { type: "separator" },
        item(win, tr("tagNext"), "edit.tag-next", "CmdOrCtrl+T"),
        item(win, tr("tagPainter"), "edit.tag-painter", "CmdOrCtrl+Shift+T"),
        { type: "separator" },
        item(win, tr("createGlossary"), "edit.glossary", "CmdOrCtrl+Shift+G"),
        item(win, tr("search"), "edit.search", "CmdOrCtrl+F"),
        item(win, tr("replaceInProject"), "edit.replace", "CmdOrCtrl+K"),
        item(win, tr("searchDict"), "edit.dict", "Alt+Shift+D"),
        { type: "separator" },
        {
          label: tr("switchCase"),
          submenu: [
            item(win, tr("caseLower"), "edit.case-lower"),
            item(win, tr("caseUpper"), "edit.case-upper"),
            item(win, tr("caseTitle"), "edit.case-title"),
            item(win, tr("caseSentence"), "edit.case-sentence"),
            item(win, tr("caseCycle"), "edit.case-cycle", "Shift+F3"),
          ],
        },
        {
          label: tr("selectMatch"),
          submenu: [
            item(win, tr("matchPrev"), "edit.match-prev", "CmdOrCtrl+Up"),
            item(win, tr("matchNext"), "edit.match-next", "CmdOrCtrl+Down"),
            { type: "separator" },
            item(win, tr("match1"), "edit.match-1", "CmdOrCtrl+1"),
            item(win, tr("match2"), "edit.match-2", "CmdOrCtrl+2"),
            item(win, tr("match3"), "edit.match-3", "CmdOrCtrl+3"),
            item(win, tr("match4"), "edit.match-4", "CmdOrCtrl+4"),
            item(win, tr("match5"), "edit.match-5", "CmdOrCtrl+5"),
          ],
        },
        {
          label: tr("insertBidi"),
          submenu: [
            item(win, "LRM", "edit.lrm"),
            item(win, "RLM", "edit.rlm"),
            item(win, "LRE", "edit.lre"),
            item(win, "RLE", "edit.rle"),
            item(win, "PDF", "edit.pdf"),
          ],
        },
        { type: "separator" },
        item(win, tr("multipleDefault"), "edit.multiple-default"),
        item(win, tr("multipleAlt"), "edit.multiple-alt"),
        item(win, tr("registerUntranslated"), "edit.register-untranslated", "CmdOrCtrl+Shift+X"),
        item(win, tr("registerEmpty"), "edit.register-empty"),
        item(win, tr("registerIdentical"), "edit.register-identical", "CmdOrCtrl+Shift+S"),
      ],
    },
    {
      label: tr("menuGoto"),
      submenu: [
        item(win, tr("gotoUntranslated"), "goto.untranslated", "CmdOrCtrl+U"),
        item(win, tr("gotoTranslated"), "goto.translated", "CmdOrCtrl+Shift+U"),
        item(win, tr("nextSeg"), "goto.next", "CmdOrCtrl+N"),
        item(win, tr("prevSeg"), "goto.prev", "CmdOrCtrl+P"),
        item(win, tr("gotoNumber"), "goto.number", "CmdOrCtrl+J"),
        item(win, tr("gotoNoteNext"), "goto.note-next", "CmdOrCtrl+Alt+N"),
        item(win, tr("gotoNotePrev"), "goto.note-prev", "CmdOrCtrl+Alt+P"),
        item(win, tr("gotoUnique"), "goto.unique", "CmdOrCtrl+Shift+K"),
        item(win, tr("gotoMatchSource"), "goto.match-source", "CmdOrCtrl+Shift+M"),
        { type: "separator" },
        item(win, tr("gotoAutoNext"), "goto.auto-next", "CmdOrCtrl+Alt+,"),
        item(win, tr("gotoAutoPrev"), "goto.auto-prev", "CmdOrCtrl+Alt+Shift+,"),
        item(win, tr("gotoEnforceNext"), "goto.enforce-next", "CmdOrCtrl+Alt+."),
        item(win, tr("gotoEnforcePrev"), "goto.enforce-prev", "CmdOrCtrl+Alt+Shift+."),
        { type: "separator" },
        item(win, tr("gotoHistoryForward"), "goto.history-forward", "CmdOrCtrl+Shift+N"),
        item(win, tr("gotoHistoryBack"), "goto.history-back", "CmdOrCtrl+Shift+P"),
        item(win, tr("gotoNotes"), "goto.notes", "CmdOrCtrl+Alt+9"),
        item(win, tr("gotoEditor"), "goto.editor", "CmdOrCtrl+Alt+0"),
      ],
    },
    {
      label: tr("menuView"),
      submenu: [
        item(win, tr("markTranslated"), "view.mark-translated"),
        item(win, tr("markUntranslated"), "view.mark-untranslated"),
        item(win, tr("markParagraph"), "view.mark-paragraph"),
        item(win, tr("displaySource"), "view.display-source"),
        item(win, tr("markNonunique"), "view.mark-nonunique"),
        item(win, tr("markNoted"), "view.mark-noted"),
        item(win, tr("markNbsp"), "view.mark-nbsp"),
        item(win, tr("markWhitespace"), "view.mark-whitespace"),
        item(win, tr("markBidi"), "view.mark-bidi"),
        item(win, tr("markAuto"), "view.mark-auto"),
        item(win, tr("markGlossary"), "view.mark-glossary"),
        item(win, tr("markLt"), "view.mark-lt"),
        item(win, tr("markFont"), "view.mark-font"),
        item(win, tr("alternateTranslation"), "view.mark-alt"),
        {
          label: tr("modInfo"),
          submenu: [
            item(win, tr("modNone"), "view.mod-none"),
            item(win, tr("modSelected"), "view.mod-selected"),
            item(win, tr("modAll"), "view.mod-all"),
          ],
        },
        { type: "separator" },
        item(win, tr("restoreGui"), "view.restore-gui"),
      ],
    },
    {
      label: tr("menuTools"),
      submenu: [
        item(win, tr("issues"), "tools.issues", "CmdOrCtrl+Shift+V"),
        item(win, tr("issuesFile"), "tools.issues-file"),
        item(win, tr("stats-standard"), "tools.stats-standard"),
        item(win, tr("stats-matches"), "tools.stats-matches"),
        item(win, tr("stats-files"), "tools.stats-files"),
        { type: "separator" },
        item(win, tr("aligner"), "tools.align"),
        item(win, tr("scripts"), "tools.scripts"),
        item(win, `${tr("scripts")} 1`, "tools.script-1", "CmdOrCtrl+Alt+1"),
        item(win, `${tr("scripts")} 2`, "tools.script-2", "CmdOrCtrl+Alt+2"),
      ],
    },
    {
      label: tr("menuOptions"),
      submenu: [
        item(win, tr("prefs"), "options.prefs", "CmdOrCtrl+,"),
        { type: "separator" },
        item(win, tr("mtAutoFetch"), "options.mt-auto"),
        item(win, tr("glossaryFuzzy"), "options.glossary-fuzzy"),
        item(win, tr("dictFuzzy"), "options.dict-fuzzy"),
        item(win, tr("completerAuto"), "options.completer-auto"),
        item(win, tr("historyCompletion"), "options.history-completion"),
        item(win, tr("historyPrediction"), "options.history-prediction"),
        { type: "separator" },
        item(win, tr("filters"), "options.filters"),
        item(win, tr("segmentation"), "options.segmentation"),
        item(win, tr("editing"), "options.workflow"),
        item(win, tr("shortcuts"), "options.shortcuts"),
        item(win, tr("accessConfig"), "options.config-dir"),
      ],
    },
    {
      label: tr("menuHelp"),
      submenu: [
        item(win, tr("manual"), "help.manual", "F1"),
        item(win, tr("about"), "help.about"),
        item(win, tr("lastChanges"), "help.changes"),
        item(win, tr("log"), "help.log"),
        item(win, tr("license"), "help.license"),
        item(win, tr("checkUpdates"), "help.updates"),
        item(win, tr("tipOfDay"), "help.tip"),
      ],
    },
  ];
  return Menu.buildFromTemplate(template);
}
