import { Menu, type BrowserWindow, type MenuItemConstructorOptions } from "electron";

function send(win: BrowserWindow, action: string, payload?: unknown) {
  win.webContents.send("menu:action", action, payload);
}

function item(
  win: BrowserWindow,
  label: string,
  action: string,
  accelerator?: string,
  extra?: Partial<MenuItemConstructorOptions>,
): MenuItemConstructorOptions {
  return {
    label,
    accelerator,
    click: () => send(win, action),
    ...extra,
  };
}

/** Java `MainMenuShortcuts.properties` (ctrl → CmdOrCtrl). */
export function buildApplicationMenu(win: BrowserWindow): Menu {
  const template: MenuItemConstructorOptions[] = [
    {
      label: "Project",
      submenu: [
        item(win, "New…", "project.new", "CmdOrCtrl+Shift+N"),
        item(win, "Download Team Project…", "project.team-new"),
        item(win, "Open…", "project.open", "CmdOrCtrl+O"),
        { label: "Open Recent", role: "recentDocuments" },
        { type: "separator" },
        item(win, "Import Source Files…", "project.import"),
        item(win, "Import from MediaWiki…", "project.wiki"),
        item(win, "Reload", "project.reload", "F5"),
        item(win, "Close", "project.close", "CmdOrCtrl+Shift+W"),
        { type: "separator" },
        item(win, "Save", "project.save", "CmdOrCtrl+S"),
        { type: "separator" },
        item(win, "Commit Source Files", "project.commit-source"),
        item(win, "Commit Target Files", "project.commit-target"),
        { type: "separator" },
        item(win, "Create Translated Documents", "project.compile", "CmdOrCtrl+D"),
        item(win, "Create Current Translated Document", "project.compile-single", "CmdOrCtrl+Shift+D"),
        item(win, "Open MED…", "project.med"),
        { type: "separator" },
        item(win, "Project Properties…", "project.edit", "CmdOrCtrl+E"),
        item(win, "Project Files…", "project.files", "CmdOrCtrl+L"),
        {
          label: "Access Project Contents",
          submenu: [
            item(win, "Project Root", "project.access-root"),
            item(win, "Dictionary Folder", "project.access-dict"),
            item(win, "Glossary Folder", "project.access-glossary"),
            item(win, "Source Folder", "project.access-source"),
            item(win, "Target Folder", "project.access-target"),
            item(win, "TM Folder", "project.access-tm"),
            item(win, "Export TM Folder", "project.access-export-tm"),
            { type: "separator" },
            item(win, "Current Source Document", "project.access-current-source"),
            item(win, "Current Target Document", "project.access-current-target"),
            item(win, "Writable Glossary", "project.access-writable-glossary"),
          ],
        },
        { type: "separator" },
        { role: "quit", accelerator: "CmdOrCtrl+Q" },
      ],
    },
    {
      label: "Edit",
      submenu: [
        item(win, "Undo", "edit.undo", "CmdOrCtrl+Z"),
        item(win, "Redo", "edit.redo", "CmdOrCtrl+Y"),
        { type: "separator" },
        item(win, "Overwrite Translation", "edit.overwrite-translation", "CmdOrCtrl+R"),
        item(win, "Insert Translation", "edit.insert-translation", "CmdOrCtrl+I"),
        item(win, "Overwrite Machine Translation", "edit.overwrite-mt", "CmdOrCtrl+M"),
        item(win, "Overwrite Source", "edit.overwrite-source", "CmdOrCtrl+Shift+R"),
        item(win, "Insert Source", "edit.insert-source", "CmdOrCtrl+Shift+I"),
        item(win, "Select Source", "edit.select-source", "CmdOrCtrl+Shift+A"),
        { type: "separator" },
        item(win, "Insert Next Missing Tag", "edit.tag-next", "CmdOrCtrl+T"),
        item(win, "Tag Painter", "edit.tag-painter", "CmdOrCtrl+Shift+T"),
        { type: "separator" },
        item(win, "Create Glossary Entry…", "edit.glossary", "CmdOrCtrl+Shift+G"),
        item(win, "Search Project…", "edit.search", "CmdOrCtrl+F"),
        item(win, "Replace in Project…", "edit.replace", "CmdOrCtrl+K"),
        item(win, "Search Dictionary", "edit.dict", "Alt+Shift+D"),
        { type: "separator" },
        {
          label: "Switch Case To",
          submenu: [
            item(win, "Lower Case", "edit.case-lower"),
            item(win, "Upper Case", "edit.case-upper"),
            item(win, "Title Case", "edit.case-title"),
            item(win, "Sentence Case", "edit.case-sentence"),
            item(win, "Cycle Case", "edit.case-cycle", "Shift+F3"),
          ],
        },
        {
          label: "Select Match",
          submenu: [
            item(win, "Previous Match", "edit.match-prev", "CmdOrCtrl+Up"),
            item(win, "Next Match", "edit.match-next", "CmdOrCtrl+Down"),
            { type: "separator" },
            item(win, "Match 1", "edit.match-1", "CmdOrCtrl+1"),
            item(win, "Match 2", "edit.match-2", "CmdOrCtrl+2"),
            item(win, "Match 3", "edit.match-3", "CmdOrCtrl+3"),
            item(win, "Match 4", "edit.match-4", "CmdOrCtrl+4"),
            item(win, "Match 5", "edit.match-5", "CmdOrCtrl+5"),
          ],
        },
        {
          label: "Insert Unicode Control Character",
          submenu: [
            item(win, "LRM", "edit.lrm"),
            item(win, "RLM", "edit.rlm"),
            item(win, "LRE", "edit.lre"),
            item(win, "RLE", "edit.rle"),
            item(win, "PDF", "edit.pdf"),
          ],
        },
        { type: "separator" },
        item(win, "Multiple Default", "edit.multiple-default"),
        item(win, "Multiple Alternate", "edit.multiple-alt"),
        item(win, "Register Untranslated", "edit.register-untranslated", "CmdOrCtrl+Shift+X"),
        item(win, "Register Empty", "edit.register-empty"),
        item(win, "Register Identical", "edit.register-identical", "CmdOrCtrl+Shift+S"),
      ],
    },
    {
      label: "Go To",
      submenu: [
        item(win, "Next Untranslated Segment", "goto.untranslated", "CmdOrCtrl+U"),
        item(win, "Next Translated Segment", "goto.translated", "CmdOrCtrl+Shift+U"),
        item(win, "Next Segment", "goto.next", "CmdOrCtrl+N"),
        item(win, "Previous Segment", "goto.prev", "CmdOrCtrl+P"),
        item(win, "Segment Number…", "goto.number", "CmdOrCtrl+J"),
        item(win, "Next Segment with a Note", "goto.note-next", "CmdOrCtrl+Alt+N"),
        item(win, "Previous Segment with a Note", "goto.note-prev", "CmdOrCtrl+Alt+P"),
        item(win, "Next Unique Segment", "goto.unique", "CmdOrCtrl+Shift+K"),
        item(win, "Match Source Segment", "goto.match-source", "CmdOrCtrl+Shift+M"),
        { type: "separator" },
        item(win, "Next Auto-Populated", "goto.auto-next", "CmdOrCtrl+Alt+,"),
        item(win, "Previous Auto-Populated", "goto.auto-prev", "CmdOrCtrl+Alt+Shift+,"),
        item(win, "Next Enforced", "goto.enforce-next", "CmdOrCtrl+Alt+."),
        item(win, "Previous Enforced", "goto.enforce-prev", "CmdOrCtrl+Alt+Shift+."),
        { type: "separator" },
        item(win, "Forward in History", "goto.history-forward", "CmdOrCtrl+Shift+N"),
        item(win, "Back in History", "goto.history-back", "CmdOrCtrl+Shift+P"),
        item(win, "Notes Panel", "goto.notes", "CmdOrCtrl+Alt+9"),
        item(win, "Editor Panel", "goto.editor", "CmdOrCtrl+Alt+0"),
      ],
    },
    {
      label: "View",
      submenu: [
        item(win, "Mark Translated Segments", "view.mark-translated"),
        item(win, "Mark Untranslated Segments", "view.mark-untranslated"),
        item(win, "Mark Paragraph Start", "view.mark-paragraph"),
        item(win, "Display Segment Source", "view.display-source"),
        item(win, "Mark Non-Unique Segments", "view.mark-nonunique"),
        item(win, "Mark Noted Segments", "view.mark-noted"),
        item(win, "Mark NBSP", "view.mark-nbsp"),
        item(win, "Mark Whitespace", "view.mark-whitespace"),
        item(win, "Mark Bidi", "view.mark-bidi"),
        item(win, "Mark Auto-Populated", "view.mark-auto"),
        item(win, "Mark Glossary Matches", "view.mark-glossary"),
        item(win, "Mark Language Checker", "view.mark-lt"),
        item(win, "Font Fallback", "view.mark-font"),
        item(win, "Mark Alternative Translations", "view.mark-alt"),
        {
          label: "Modification Info",
          submenu: [
            item(win, "None", "view.mod-none"),
            item(win, "Selected Segment", "view.mod-selected"),
            item(win, "All Segments", "view.mod-all"),
          ],
        },
        { type: "separator" },
        item(win, "Restore Default GUI", "view.restore-gui"),
      ],
    },
    {
      label: "Tools",
      submenu: [
        item(win, "Check Issues", "tools.issues", "CmdOrCtrl+Shift+V"),
        item(win, "Check Issues for Current File", "tools.issues-file"),
        item(win, "Statistics", "tools.stats-standard"),
        item(win, "Match Statistics", "tools.stats-matches"),
        item(win, "Match Statistics per File", "tools.stats-files"),
        { type: "separator" },
        item(win, "Align Files…", "tools.align"),
        item(win, "Scripting…", "tools.scripts"),
        item(win, "Script slot 1", "tools.script-1", "CmdOrCtrl+Alt+1"),
        item(win, "Script slot 2", "tools.script-2", "CmdOrCtrl+Alt+2"),
      ],
    },
    {
      label: "Options",
      submenu: [
        item(win, "Preferences…", "options.prefs", "CmdOrCtrl+,"),
        { type: "separator" },
        item(win, "Auto-fetch Machine Translations", "options.mt-auto"),
        item(win, "Glossary Fuzzy Matching", "options.glossary-fuzzy"),
        item(win, "Dictionary Fuzzy Matching", "options.dict-fuzzy"),
        item(win, "Show Auto-completer Automatically", "options.completer-auto"),
        item(win, "History Completion", "options.history-completion"),
        item(win, "History Prediction", "options.history-prediction"),
        { type: "separator" },
        item(win, "File Filters…", "options.filters"),
        item(win, "Segmentation Setup…", "options.segmentation"),
        item(win, "Editing Behaviour…", "options.workflow"),
        item(win, "Keyboard Shortcuts…", "options.shortcuts"),
        item(win, "Access Configuration Folder", "options.config-dir"),
      ],
    },
    {
      label: "Help",
      submenu: [
        item(win, "User Manual", "help.manual", "F1"),
        item(win, "About OmegaT", "help.about"),
        item(win, "Last Changes", "help.changes"),
        item(win, "Log…", "help.log"),
        item(win, "License", "help.license"),
        item(win, "Check for Updates", "help.updates"),
        item(win, "Tip of the Day", "help.tip"),
      ],
    },
  ];
  return Menu.buildFromTemplate(template);
}
